language: groovy
sudo: false
jdk:
- oraclejdk7
env:
  global:
  - secure: RxdKs4qrXJ4wLoqjP2JnLNUPVN8boRPs4LeKj28yAEn9Dgj9Z98DoEa4sVLbCo/9Rk0NvQ0iXzRNYqx0qlkWSNgC4IipP32f9EW1ewcgeiofzipAqLjViwsT38gfPUmEMJkfxh3I1RNr3GqgQtgGN//TZ7PLr1NVTlsxECzcbuY0RKS76QAOqZpAjbaeAczHba/NcOi61FqqZxe3MepOXkwIJguBi1rhNWneQdBHHdIpQ0gpdfu+89thEz0YP4joMlt6MsN4FJ2Zwn6r+UYqmBGpzzQuZ+ed3v5RxQT62gfWcM6KrWYnUnvC+3aVtKwDwbI25ndG4l6u9tf8L689h4XbTDwVjTXySuYcNn4DnPYIX9bYsoXNnn5jO2sl9VJ3eL9kZwi+bXCicqe2DAzIEHPavziPvF85Vf/SDxOKqedpypb07aAUODeFfQoCnK3m9oDqgKOyb311vjZhWyJHYKZZBtBJjHjE1e5JfI6WjtEGMshOyPEKw6EqioM3RSdjiIfa8RPvP2VH0FcGmh8YCOaUtF7AcNAIkwG60wFL/+tgAaxc/SnVzZy1yiqP1xzkcC841qT/11xyu1VWzxqZgXKtdfQPLRaySSLKU7++JASKuwYfyzftQqUkoqKIJ22oag7bxriUVVI8XHCkPQicsW0vvFo9ENIeH1vPXa8QkG8=
  - secure: LUib/DRYZYLIy9b0OAf9e+LMSS+eePhbOgdCrEeW7nWuc01oouphwErbwUoNkle1E2fY5f+EpfY2EXOChYpe8qchap8OOsnXlKd8rw7s0SRN0sRt0/EqvHOP5Z5Ud9EqGwazApSXrMYcI10dffvE0S2+xWaTd+Ria22XnuGfpYwf9yU4gRknlm+pHG2nY9/3smWrPz8xDuE+Sspk9ItLRHtXQQJ3QxbpBL1LfD2EfukfZwHG5znVGF+KwfYq2z3gBaVQr75VUQuDJPxSbTbyPnqAjxfw9Fa/jNUsviUt48/5scDl4ZI/VSy5efMxQu9wMPyAwSMg3oGqK3u1WA6W9hwXL1Y8pxyuyQW+Z3m0Bda19oQQWgr7HA3mHxn0XDvJVg2oAn+1za2TloeHsnlgaPFjwJXjKofB3OGcFphJ+8aDvaj5qEZz2fJI4fdy9bAfjP7xUs4+63U44ibXF3zQezOBruiQMHXTO3M0WaBRWWHPRw8HW3Icb+9TTpESUv/9cmqnaAdrYSFywuCgeL7pe1BG8Y6ymhX9LOoDYvTe+3Hh8YzJn+3YwDWIQNvkaRqRLmeruVq5eBibL7y7FcVW4OPVkxqda2s3IWizNQQIN7+hxbdvBO0GmN8vhqOOCKi+0bmB+8X3MB34opVjA8GS6G0SLjynnMXXa8R4bfNhOH0=
before_script:
- chmod +x gradlew
- chmod +x travis-build.sh
- chmod +x travis-publish.sh
script: ./travis-build.sh
after_success:
- ./travis-publish.sh
notifications:
  slack:
    secure: CH8XkPAueZBVF60DaFRAM6ajNiG3mRCBZFlRbNd5Ya1ivPUSKYJQp1jJVoSQizd4EabEbK1/1+dDwBm+OiEoNN3FAzkleC8DZNSh/EjmQT2RArLZrv41dx2RlKkMyB0oF16mN6ivDGQofqDqBNDcWOZGpgnewGMgHMWtEluAOrA=
